rm(list=ls())

load('Model1.RData')
library(rstan)


#extr_outs = function(model, effects, res.het = FALSE)


# Extract stan results - A função inicia aqui
out <- rstan::extract(Model1, permuted = TRUE)

effects = c('r', 'b', 'g', 'gl', 'l')

# Posterior effects
post = list()
for (i in effects) {
  post[[i]] = out[[i]]
}
rm(i)

# Data generated by the model
y_gen_post <- out[['y_gen']]

if(res.het == F){
  # Variances
  variances = NULL
  for (i in c(effects,'sigma')) {
    all_variances = out[[paste("s",i,sep='_')]]
    variances[i] = mean(all_variances)
  }
  variances = data.frame(
    effect = c(effects,'res'),
    var = variances,
    row.names = NULL
  )
  rm(all_variances)
  rm(i)
} else {
  sigmaENV <- data.frame(Env = paste0('Env_',unique(index)),
                         Sigma_hat = apply(out$sigma^2, 2, mean)) 
}



# Maximum posterior values (MAP)
get_map <- function(posterior) {
  posterior <- as.matrix(posterior) 
  if (ncol(posterior) > 1) {
    den = apply(posterior, 2, density)
    map = unlist(lapply(den, function(den)
      den$x[which.max(den$y)]))
  }
  else {
    den = density(posterior)
    map = den$x[which.max(den$y)]
  }
  return(map)
}
map = lapply(post, get_map)

results = list(post, variances, map)

return(results)















