########################################################################################################################
##                                                                                                                    ##                                        
##                                                                                                                    ##
##  Bayesian Analysis for MET data                                                                                    ##
##  Date: Feb, 2022                                                                                                   ##
##                                                                                                                    ##
##  Leveraging probability concepts for cultivar recommendation in multi‑environment trials                           ##
##  Dias et al. 2022. Model 4 (M4)                                                                                    ##
##                                                                                                                    ##
##  Authors:    KOG Dias        <kaio.o.dias@ufv.br>                                                                  ##
##              JPR dos Santos  <jhowpd@gmail.com>                                                                    ##
##              MD Krause       <krause.d.matheus@gmail.com>                                                          ##
##                                                                                                                    ##
########################################################################################################################



# Extract stan results
out <- rstan::extract(Model4, permuted = TRUE)

# Subset replication posterior effects
r_post <- out$r

# Subset blocks posterior effects
b_post <- out$b

# Subset hybrids posterior effects
g_post <- out$g
dim(g_post)

# Subset hybrids by location posterior effects
gl_post <- out$gl
dim(gl_post)

# Subset hybrids by region posterior effects
gm_post <- out$gm
dim(gm_post)

# Subset data generated by the model
y_gen_post <- out$y_gen

# Subset the replication variance
s2_r_post <- (out$s_r)^2
mean(s2_r_post) # block variance

# Subset the block variance
s2_b_post <- (out$s_b)^2
mean(s2_b_post) # block variance

# Subset the genotype (genetic) variance
s2_g_post <- (out$s_g)^2
mean(s2_g_post) # Genetic variance

# Subset the genotype by location variance
s2_gl_post <- (out$s_gl)^2
mean(s2_gl_post) # Genetic by location variance

# Subset the location variance
s2_l_post <- (out$s_l)^2
mean(s2_l_post) # location variance

# Subset the Region variance
s2_m_post <- (out$s_m)^2
mean(s2_m_post) # Region variance

# Subset the genotype by Region variance
s2_gm_post <- (out$s_gm)^2
mean(s2_gm_post) # Genetic by Region variance

# Subset the error variance by environment
sigmaENV <- data.frame(Env = paste0('Env_',unique(index)),
                       Sigma_hat = apply(out$sigma^2, 2, mean)) 

# Getting maximum a posteriori values (MAP)
source('get_map.R') # Function to obtain the maximum a posteriori (MAP) value

# For the replication effects
r_map <- get_map(r_post)

# For the block effects
b_map <- get_map(b_post)

# For the genotype effects
g_map <- get_map(g_post)

# For the genotype by location effects
gl_map <- get_map(gl_post)

# For the genotype by region effects
gm_map <- get_map(gm_post)







